<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../../assets/css/style.css?v=<?= time() ?>">
    <title>OKR <?php echo  '- ' . $_SESSION['title']; ?></title>
    <script src="../../../assets/jQuery/jquery-3.7.0.min.js" type="text/javascript"></script>
</head>
<body>

<div class="nav">
    <input type="checkbox" id="nav-check">
    <div class="nav-header">
        <div class="nav-title">
            OKR admin
        </div>
    </div>
    <div class="nav-btn">
        <label for="nav-check">
            <span></span>
            <span></span>
            <span></span>
        </label>
    </div>

    <div class="nav-links">
        <a href="/home">Home</a>
        <a href="/objective">My objective</a>
        <a href="http://stackoverflow.com/users/4084003/">My key results</a>
    </div>
</div>