version: "3"
services:
  app:
    build:
        context: ./bin/app
    container_name: ${COMPOSER_PROJECT_NAME}_app
    working_dir: /usr/share/nginx/html
    external_links:
      - mysql
      - redis
    networks:
      - container_default
    volumes:
      - ${DOCUMENT_ROOT-./www}:/usr/share/nginx/html
      - ./config/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./config/php/dev.ini:/usr/local/etc/php/conf.d/dev.ini
  cli:
      build:
        context: ./bin/cli
      container_name: ${COMPOSER_PROJECT_NAME}_cli
      working_dir: /usr/share/nginx/html
      external_links:
        - mysql
        - redis
      networks:
        - container_default
      volumes_from:
        - app
  nginx:
    build:
      context: ./bin/nginx
    container_name: ${COMPOSER_PROJECT_NAME}_webserver
    links:
      - app
    depends_on:
      - app
    ports:
      - "8100:80"
    networks:
      - container_default
    volumes_from:
      - app
    volumes:
      - ${VHOSTS_DIR-./config/nginx/sites-enabled}:/etc/nginx/conf.d
      - ${LOG_DIR-./logs/nginx}:/var/log/nginx
networks:
  container_default:
    external: true
