<?php include_once '../app/Views/Layout/mainHome.phtml'?>

<section class="container mt-20">
    <div class="btn-group align-left">
        <a href="/objective-views/newObjective" class="btn">Novo objetivo</a>
    </div>
    <hr>

    <div class="cards">
        <?php foreach ($args['objective'] as $objective): ?>
            <div class="card-objective">

                <h3><?php echo $objective['title'] ?></h3>
                <p>Clique no botão abaixo para ver os resultados chaves de seu objetivo.</p>
                <p><b>Status: </b><?php echo $objective['status'] == 0 ? 'Em progresso' : 'Finalizado' ?></p>
                <hr>
                <div class="btn-group align-center">
                    <a href="/key-result-views/list/<?php echo $objective['id'] ?>" class="btn">Detalhes</a>
                    <a href="/objective-views/edit/<?php echo $objective['id'] ?>" class="btn">Editar</a>
                    <a href="/objective-views/finishObjective/<?php echo $objective['id'] ?>" class="btn">Finalizar</a>
                </div>
                <div class="btn-group align-center">
                    <?php if ($objective['deleted_at'] === null): ?>
                        <a href="/objective-views/remove/<?php echo $objective['id'] ?>" class="btn-danger">Apagar</a>
                    <?php else: ?>
                        <a href="/objective-views/restoreObjective/<?php echo $objective['id'] ?>" class="btn-danger">Restaurar</a>
                    <?php endif;?>
                </div>

            </div>
        <?php endforeach; ?>
    </div>
</section>

<?php include_once '../app/Views/Layout/mainEnd.phtml'?>