<?php include_once '../app/Views/Layout/mainHome.phtml'?>

<section class="container mt-20 row">
    <div class="card mt-200">
        <div class="card-alert d-none" id="response"></div>
        <h2>Novo objetivo</h2>
        <form method="POST" id="objective_form">
            <div class="form-group">
                <label for="title" class="form-group-label">Título: </label>
                <input type="text" placeholder="Título do seu objetivo" id="title" name="title" required>
            </div>
            <div class="form-group">
                <label for="description" class="form-group-label">Descrição: </label>
                <textarea id="description" name="description" rows="4" cols="40">

                </textarea>
            </div>
            <hr>

            <div class="btn-group text-center">
                <a href="#" id="btn_register_objective" class="btn">Cadastrar</a>
            </div>
        </form>
    </div>
</section>
    <script src="../../../assets/js/objective.js" type="text/javascript"></script>
<?php include_once '../app/Views/Layout/mainEnd.phtml'?>