<?php include_once '../app/Views/Layout/mainHome.phtml'?>

<section class="container mt-20 row">
    <div class="card mt-200">
        <div class="card-alert d-none" id="response"></div>
        <h2>Novo objetivo</h2>
        <?php include_once '_formObjective.phtml'?>
        <div class="btn-group text-center">
            <a href="#" id="btn_register_objective" class="btn">Cadastrar</a>
        </div>
    </div>
</section>
<script src="../../../assets/js/objective.js" type="text/javascript"></script>
<?php include_once '../app/Views/Layout/mainEnd.phtml'?>