<?php include_once '../app/Views/Layout/mainHome.phtml'?>

    <section class="container mt-20 row">
        <div class="card mt-200">
            <div class="card-alert d-none" id="response"></div>
            <input type="hidden" value="<?php echo $args['objective'][0]['id']?>" name="id" id="objective_id">
            <h2>Restaurando o objetivo</h2>
            <p><b>Título:</b> <?php echo $args['objective'][0]['title'] ?></p>
            <p>Deseja realmente restaurar o objetivo?</p>

            <div class="btn-group text-center">
                <a href="#" id="btn_restore_objective" class="btn-danger">Sim</a>
                <a href="/objective" class="btn">Não</a>
            </div>

        </div>
    </section>
    <script src="../../../assets/js/objective.js" type="text/javascript"></script>
<?php include_once '../app/Views/Layout/mainEnd.phtml'?>