<?php include_once '../app/Views/Layout/mainHome.phtml'?>

<main class="container">
    <section class="form text-center">
        <h2>Login</h2>
        <form method="POST" id="login-form" >
            <div class="">
                <label for="email">
                    <span>Email: </span>
                    <input type="email" placeholder="Digite aqui o e-mail" id="email" name="email" value=""  autofocus>
                </label>
            </div>
            <div>
                <label for="password">
                    <span>Senha: </span>
                    <input type="password" placeholder="Digite aqui a senha" id="password" name="password" value="" >
                </label>
            </div>

            <div>
                <button class="btn" type="submit">
                    Logar
                </button>
            </div>
        </form>
        <a href="cadastro.php" class="btn">Cadastrar</a>
    </section>
</main>

<?php include_once '../app/Views/Layout/mainEnd.phtml'?>
