<?php include_once '../app/Views/Layout/mainHomeLogin.phtml'?>

<main class="container">
    <section class="text-center row">
        <div class="card mt-200">
            <div class="card-alert d-none" id="response"></div>
            <h2>Login</h2>
            <form method="POST" id="login_form">
                <div class="form-group">
                    <label for="email" class="form-group-label">Email: </label>
                    <input type="email" placeholder="Seu e-mail" id="email" name="email" required>
                </div>
                <div class="form-group">
                        <label for="password" class="form-group-label">Password: </label>
                        <input type="password" placeholder="Sua senha" id="password" name="password" required>
                </div>
                <hr>

                <div class="btn-group">
                    <a href="#" id="btn_logar" class="btn">Logar</a>
                    <a href="#" id="btn_register" class="btn">Register</a>
                </div>

            </form>
        </div>
    </section>
</main>
<script src="../../../assets/js/login.js" type="text/javascript"></script>
<?php include_once '../app/Views/Layout/mainEndLogin.phtml'?>
