<?php include_once '../app/Views/Layout/mainHome.phtml'?>

<main class="container">
    <section class="form text-center row">
        <div class="card mt-200">
            <h2>Login</h2>
            <form method="POST" id="login_form" >
                <div>
                    <label for="email" class="form-group-label">Email: </label>
                    <input type="email" class="form-group-input" placeholder="Digite aqui o e-mail" id="email" name="email" value="" required autofocus>
                </div>
                <div>
                        <label for="password" class="class="form-group-label">Senha: </label>
                        <input type="password" placeholder="Digite aqui a senha" id="password" name="password" value="" required>
                </div>

                <div class="btn-group">
                    <a href="#" id="btn_logar" class="btn">Logar</a>
                    <a href="cadastro.php" class="btn">Register</a>
                </div>

            </form>
        </div>
    </section>
</main>
<script src="../../../assets/js/login.js" type="text/javascript"></script>
<?php include_once '../app/Views/Layout/mainEnd.phtml'?>
