<?php include_once '../app/Views/Layout/mainHomeLogin.phtml'?>
<main class="container">
    <section class="text-center row">
        <div class="card mt-200">
            <div class="card-alert d-none" id="response"></div>
            <h2>Register user</h2>
            <form method="POST" id="register_form">
                <div class="form-group">
                    <label for="name" class="form-group-label">Name: </label>
                    <input type="text" placeholder="Your name" id="name" name="name" required>
                </div>
                <div class="form-group">
                    <label for="email" class="form-group-label">Email: </label>
                    <input type="email" placeholder="Your e-mail" id="email" name="email" required>
                </div>
                <div class="form-group">
                    <label for="password" class="form-group-label">Password: </label>
                    <input type="password" placeholder="Your password" id="password" name="password" required>
                </div>
                <div class="form-group">
                    <label for="password" class="form-group-label">Confirm password: </label>
                    <input type="password" placeholder="Confirm password" id="password" name="confirmPassword" required>
                </div>
                <hr>

                <div class="btn-group">
                    <a href="#" id="btn_register" class="btn">Register</a>
                    <a href="/" id="btn_register" class="btn">Voltar</a>
                </div>

            </form>
        </div>
    </section>
</main>
<script src="../../../assets/js/user.js" type="text/javascript"></script>
<?php include_once '../app/Views/Layout/mainEndLogin.phtml'?>